# CI/CD Pipeline for QA

# This is used for versioning
name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

# Triggers for this pipeline
# This pipeline is batched, so multiple triggers in rapid succession will be grouped together as a single run
# Documentation files will not trigger a build
trigger:
  batch: true
  branches:
    include:
    - qa
  paths:
    exclude:
    - '*.md'
    - 'README.md'

# Pull requests to master and any branch under "releases/" will trigger a build
# The deployment stage will not be triggered by pull requests
pr: 
- master
- releases/*

# The CI/CD Stages
stages:

# CI - Build
- template: templates/build.yml
  parameters:
    configuration: Release
    solution: MySolution.sln

# CD - Deploy CM Instance
- template: templates/deploy.yml
parameters:
  environment: CM
  # This should be the name of the Az service connection 
  # configured in the Azure DevOps project settings
  azSubscription: 'My Azure Subscription'
  # This should be the name of the Az resource group to deploy to
  azResourceGroup: 'mysite-prod'
  # This should be the name of the Az app service
  azAppname: 'mysite-cm'

# CD - Deploy CD Instance
- template: templates/deploy.yml
  parameters:
    environment: CD
    # This should be the name of the Az service connection 
    # configured in the Azure DevOps project settings
    azSubscription: 'My Azure Subscription'
    # This should be the name of the Az resource group to deploy to
    azResourceGroup: 'mysite-prod'
    # This should be the name of the Az app service
    azAppname: 'mysite-cd'